### ISSUE TITLE
请问sbi_call是在哪里实现的？

### ISSUE THREAD

**Issue by Ingsuifon** [i-Pear/SysCore#1]
不好意思，问一个愚蠢的问题，我看到的一个指导说明里说这个函数内联了汇编代码来执行ecall，但是我在sbi.h里只看到了extern而并没有在其它C文件找到实现。

**Comment by i-Pear** [comment]
是在boot.s里使用汇编实现的 具体在：https://github.com/i-Pear/SysCore/blob/main/src/asm/boot.s#L57

**Comment by Ingsuifon** [comment]
> 是在boot.s里使用汇编实现的 具体在：https://github.com/i-Pear/SysCore/blob/main/src/asm/boot.s#L57

谢谢。
